# **Importing Dataset**

In [ ]:
import kagglehub
path = kagglehub.dataset_download("sopanmagar/moviesmetadata")
path

Using Colab cache for faster access to the 'moviesmetadata' dataset.

'/kaggle/input/moviesmetadata'

# **Apply EDA **
Here we apply EDA and checking NUll Values and Cleaning Data and Using Columns that are Important.

In [ ]:
import pandas as pd

In [ ]:
path="/kaggle/input/moviesmetadata/archive/movies_metadata.csv"


movies_df = pd.read_csv(path1)

/tmp/ipykernel_1370/3510531588.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_df = pd.read_csv(path1)

In [ ]:
movies_df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
movies_df = movies_df.drop_duplicates(subset='title')[
    ['title', 'overview', 'genres','tagline','release_date',
     'runtime', 'vote_average','popularity']
]

In [ ]:
movies_df.head()

,title,overview,genres,tagline,release_date,runtime,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,1995-10-30,81.0,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,1995-12-15,104.0,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,1995-12-22,101.0,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,1995-12-22,127.0,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,1995-02-10,106.0,5.7,8.387519

In [ ]:
movies_df.isna().sum()

title               1
overview          915
genres              0
tagline         23226
release_date       82
runtime           251
vote_average        1
popularity          1
dtype: int64

In [ ]:
movies_df = movies_df.dropna(subset= "title")
movies_df[['overview','release_date','runtime','tagline']] = movies_df[['overview','release_date','runtime','tagline']].fillna(" ")

In [ ]:
movies_df.isna().sum()

title           0
overview        0
genres          0
tagline         0
release_date    0
runtime         0
vote_average    0
popularity      0
dtype: int64

In [ ]:
movies_df.shape

(42277, 8)

In [ ]:
movies_df['genres'].iloc[0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
import ast
movies_df['genres'] = movies_df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [ ]:
movies_df.head()

,title,overview,genres,tagline,release_date,runtime,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,1995-10-30,81.0,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,1995-12-15,104.0,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,1995-12-22,101.0,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,1995-12-22,127.0,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,1995-02-10,106.0,5.7,8.387519

In [ ]:
movies_df['tags'] = movies_df['overview'] + " "+movies_df['genres']+" "+movies_df['tagline']
movies_df.head()

,title,overview,genres,tagline,release_date,runtime,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,1995-10-30,81.0,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,1995-12-15,104.0,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,1995-12-22,101.0,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,1995-12-22,127.0,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,1995-02-10,106.0,5.7,8.387519,Just when George Banks has recovered from his ...

# **Apply NLP**

Here We apply NLP to convert the text into numbers as we know computer doest understand the english it understand Bianary after applying NLP we we create a function and then apply cosine similarity so that we easliy find movies according to our search

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
stop_words = stopwords.words("english")
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
  #Lowercase
  text = str(text). lower()
  #removed the punctuations
  text = re.sub(r' [^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer. lemmatize(word) for word in words]

  return " ".join(words)

In [ ]:
movies_df['tags'] = movies_df['tags'].apply(preprocess_text)

In [ ]:
movies_df.reset_index(drop = True,inplace=True)

In [ ]:
Here we create a sperate series for tiles so that we can pass to our function and that we created to find the maching movies index or title

In [ ]:
indices = pd.Series(movies_df. index, index = movies_df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Caged Heat 3000                42272
Subdue                         42273
Century of Birthing            42274
Satan Triumphant               42275
Queerama                       42276
Length: 42277, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
tfidf = TfidfVectorizer(max_features=50000,stop_words='english',ngram_range=(1,2))
tfidf_matrix = tfidf.fit_transform(movies_df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1445160 stored elements and shape (42277, 50000)>

In [ ]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix). flatten()
  similar_idx = sim_score.argsort() [ ::- 1] [1:n+1]
  return movies_df['title'].iloc[similar_idx]

In [ ]:
recommend("Hulk")

21683                                             Ultraman
37271    UFO... annientare S.H.A.D.O. stop. Uccidete St...
4780                          The Incredible Shrinking Man
3331                                 The Hideous Sun Demon
26724                               France société anonyme
40955                                  Nightmare City 2035
19441                                               Désiré
20304                     The Death of the Incredible Hulk
12582                                              Fallout
812                                         Chain Reaction
Name: title, dtype: object

In [ ]:
Here we create models of these files so that we can use them in our app

In [ ]:
import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

movies_df.to_pickle('data.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))